language: android
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-27

android:
  components:

    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - $ANDROID_TARGET

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

# Caching in Gradle means that to avoid uploading the cache after every build
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  # Install the new version of the android-27 package
  - yes | sdkmanager "platforms;android-27"
  # Prevent ./gradlew: Permission denied
  - chmod +x gradlew

#Build, and run tests
script:
  - ./gradlew build test
